apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-conf
  namespace: dtest
data:
  servers.json: |
    {
      "Servers": {
        "1": {
        "Name": "test server",
        "Group": "Servers",
        "Host": "postgres",
        "Port": 5432,
        "MaintenanceDB": "postgres",
        "Username": "admin",
        "SSLMode": "prefer"
          }
      }
    }

